import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e)));
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('http://localhost:4173/', { waitUntil: 'load' });
await p.waitForSelector('#hero-blob-canvas');
await p.waitForTimeout(2600);
const strip = { x: 90, y: 300, width: 480, height: 240 };
const shot = async (x, y, ms = 1500) => { await p.mouse.move(x, y); await p.waitForTimeout(ms); return p.screenshot({ clip: strip }); };
const inL = await shot(120, 450);
const inR = await shot(540, 450);
console.log(`over the portrait, left vs right   -> moves: ${!inL.equals(inR)}   (want true)`);
const outA = await shot(1000, 450);
const outB = await shot(1380, 780);
const outC = await shot(1200, 200);
console.log(`away from it, two positions        -> moves: ${!outA.equals(outB)}   (want false)`);
console.log(`away from it, third position same  -> ${outA.equals(outC)}   (want true)`);
console.log(errs.length ? 'errors: ' + errs[0] : 'no shader/console errors');
await b.close();
